UNIT_CONFIG = {
    1: {
        "name": "酸液源石虫·α",
        "damage_type": "物理",
        "attack": 435,
        "defense": 0,
        "health": 1390,
        "magic_resist": 0,
        "attack_interval": 3.3,
        "move_speed": 1 / 2, # 除2是因为方舟就是要除2
        "attack_radius": 2.75,
        "effect": "破甲15",
        "icon": "images/monster/1.png"
    },
    2: {
        "name": "灼热源石虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    3: {
        "name": "狂暴的猎狗pro",
        "damage_type": "物理",
        "attack": 555,
        "defense": 0,
        "health": 1500,
        "magic_resist": 20,
        "attack_interval": 1.4,
        "move_speed": 1.9 / 2,
        "attack_radius": 0.8,
        "effect": "",
        "icon": "images/monster/3.png"
    },
    4: {
        "name": "炮击组长",
        "damage_type": "物理",
        "attack": 825,
        "defense": 150,
        "health": 2500,
        "magic_resist": 0,
        "attack_interval": 4.5,
        "move_speed": 0.8 / 2,
        "attack_radius": 7,
        "effect": "溅射",
        "icon": "images/monster/4.png"
    },
    5: {
        "name": "萨卡兹大剑手",
        "damage_type": "物理",
        "attack": 900,
        "defense": 230,
        "health": 3750,
        "magic_resist": 50,
        "attack_interval": 2,
        "move_speed": 0.85 / 2,
        "attack_radius": 0.8,
        "effect": "",
        "icon": "images/monster/5.png"
    },
    6: {
        "name": "宿主流浪者",
        "damage_type": "物理",
        "attack": 975,
        "defense": 200,
        "health": 5500,
        "magic_resist": 30,
        "attack_interval": 3,
        "move_speed": 0.65 / 2,
        "attack_radius": 0.8,
        "effect": "再生",
        "icon": "images/monster/6.png"
    },
    7: {
        "name": "重装防御者",
        "damage_type": "物理",
        "attack": 900,
        "defense": 800,
        "health": 3000,
        "magic_resist": 0,
        "attack_interval": 2.6,
        "move_speed": 0.75 / 2,
        "attack_radius": 0.8,
        "effect": "",
        "icon": "images/monster/7.png"
    },
    8: {
        "name": "复仇者",
        "damage_type": "物理",
        "attack": 720,
        "defense": 230,
        "health": 9000,
        "magic_resist": 50,
        "attack_interval": 2.3,
        "move_speed": 0.65 / 2,
        "attack_radius": 0.8,
        "effect": "火刀",
        "icon": "images/monster/8.png"
    },
    9: {
        "name": "狂暴宿主组长",
        "damage_type": "物理",
        "attack": 2625,
        "defense": 230,
        "health": 15000,
        "magic_resist": 30,
        "attack_interval": 1.3,
        "move_speed": 1.2 / 2,
        "attack_radius": 0.8,
        "effect": "掉血",
        "icon": "images/monster/9.png"
    },
    10: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    11: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    12: {
        "name": "泥岩巨像",
        "damage_type": "物理",
        "attack": 4500,
        "defense": 700,
        "health": 50000,
        "magic_resist": 30,
        "attack_interval": 7,
        "move_speed": 0.4 / 2,
        "attack_radius": 0.8,
        "effect": "",
        "icon": "images/monster/12.png"
    },
    13: {
        "name": "高塔术师",
        "damage_type": "法术",
        "attack": 900,
        "defense": 160,
        "health": 3500,
        "magic_resist": 65,
        "attack_interval": 7,
        "move_speed": 0.6 / 2,
        "attack_radius": 3.2,
        "effect": "打2 溅射",
        "icon": "images/monster/13.png"
    },
    14: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    15: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    16: {
        "name": "冰原术师",
        "damage_type": "法术",
        "attack": 375,
        "defense": 200,
        "health": 2500,
        "magic_resist": 50,
        "attack_interval": 4.5,
        "move_speed": 0.7 / 2,
        "attack_radius": 3.2,
        "effect": "打2 寒冷",
        "icon": "images/monster/16.png"
    },
    17: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    18: {
        "name": "弧光锋卫长",
        "damage_type": "法术",
        "attack": 1200,
        "defense": 650,
        "health": 7000,
        "magic_resist": 50,
        "attack_interval": 3,
        "move_speed": 0.75 / 2,
        "attack_radius": 0.8,
        "effect": "",
        "icon": "images/monster/18.png"
    },
    19: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    20: {
        "name": "提亚卡乌好战者",
        "damage_type": "物理",
        "attack": 480,
        "defense": 380,
        "health": 2750,
        "magic_resist": 10,
        "attack_interval": 1,
        "move_speed": 0.8 / 2,
        "attack_radius": 0.8,
        "effect": "破甲10",
        "icon": "images/monster/20.png"
    },
    21: {
        "name": "矿脉守卫",
        "damage_type": "法术",
        "attack": 600,
        "defense": 300,
        "health": 12500,
        "magic_resist": 10,
        "attack_interval": 4,
        "move_speed": 0.6 / 2,
        "attack_radius": 0.8,
        "effect": "反伤",
        "icon": "images/monster/21.png"
    },
    22: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    23: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    24: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    25: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    },
    26: {
        "name": "巧克力流心虫虫",
        "damage_type": "法术",
        "attack": 75,
        "defense": 0,
        "health": 600,
        "magic_resist": 0,
        "attack_interval": 2,
        "move_speed": 0.8 / 2,
        "attack_radius": 2.8,
        "effect": "灼燃",
        "icon": "images/monster/2.png"
    }
}